### ISSUE TITLE
Custom file not working after OBS update

### ISSUE THREAD

**Issue by gustavobacelar** [steveseguin/twitch-youtube-restream-chat-overlay#13]
Dear Steve,
After updating OBS to version 27.2.1, the custom local file stopped working. It does not ask for the session ID anymore as it used to (I could never add "?session=XXXXXX" to the end of the browser source local file link in OBS – I do not know whether it works only in PC, I use Mac). When I try to load a comment, it only shows this GitHub website, as you can see in the attached image.

Can you help me out with this issue? Thanks for sharing your great work!
![Captura de Tela 2022-03-08 às 10 24 56](https://user-images.githubusercontent.com/4256987/157246766-d36000e2-20f1-45b2-99db-7e132dcac7cd.png)

**Comment by steveseguin** [comment]
What is the link that you are putting in the OBS browser source ?

**Comment by steveseguin** [comment]
It's possible that the new version of OBS blocks pop up.

Does something like this doesn't work in OBS?  
````
file:///Users/steveseguin/Code/social_stream/index.html?session=ffff
```

You could I suppose hard-code the session ID into the index.html file.
https://github.com/steveseguin/twitch-youtube-restream-chat-overlay/blob/a21ec0da8386a47c61358a2aece49c18a9381c98/index.html#L498
Edit the line
`roomID = prompt("Enter your session ID here, or add it to the URL.");`
to be
`roomID = "asd1234asdf";` ; change out the value for whatever your session ID is

**Comment by gustavobacelar** [comment]
> What is the link that you are putting in the OBS browser source ?

The local file link I'm using is in the attached image below. This field doesn't allow me to write anything on it, I the path to the local file using the button Explore. I was never able to write in this field, even on the previous version of OBS
![Captura de Tela 2022-03-08 às 10 49 44](https://user-images.githubusercontent.com/4256987/157251571-6d44d546-8a9b-4115-b827-255173ae3a8f.png)
.

**Comment by gustavobacelar** [comment]
When the chat overlay was working, I used to get a window asking for session ID every time I opened OBS or when I updated the chat overlay browser source. But this pop-up window doesn't appear anymore.

**Comment by steveseguin** [comment]
Please refer to how I have my OBS URL and checkboxes setup.  Please be sure that capitalization is correct

OBS 27.2 may have broken the pop up, but things should still work if the URL is correct and &session=xxxx is used.

Also note that I am using `file:///`  to begin the URL that I put into OBS.  

![image](https://user-images.githubusercontent.com/2575698/157258408-f36f59ef-21d0-4a20-a76b-77c08f639dc9.png)

**Comment by gustavobacelar** [comment]
> 

Thank you very much, it worked!! 🎉 
It was missing 'file:///' to begin the URL referring to a local file.
