### ISSUE TITLE
Mobcrush integration request

### ISSUE THREAD

**Issue by AssuntoDaVez** [steveseguin/twitch-youtube-restream-chat-overlay#6]
Mobcrush.com Chat Integration

**Comment by AssuntoDaVez** [comment]
Unlike restream.io, mobcruch does livez for facebook pages for free
https://studio.mobcrush.com/chatpopup.html

**Comment by steveseguin** [comment]
Sorry for just seeing this now; did you want me to add Mobcrush.com support? happy to

**Comment by AssuntoDaVez** [comment]
Yes. it would help a lot

**Comment by steveseguin** [comment]
I'll give it a try then. thank you for the request

**Comment by steveseguin** [comment]
I added mobcrush support to 0.9.0

You can download it here:
[](https://github.com/steveseguin/twitch-youtube-restream-chat-overlay/releases/tag/0.9.0)

To use it, once loaded, go to the page, replacing {usernamehere} with your mobcrush username.  

`https://www.mobcrush.com/{usernamehere}/chat.slobs `

Their site was down most the day, so it took a while to add.   Let me know how it goes though -- there are probably bugs.
-steve

**Comment by steveseguin** [comment]
![image](https://user-images.githubusercontent.com/2575698/131611874-1e91f396-313f-47ea-b504-bada4cfd9f42.png)

**Comment by AssuntoDaVez** [comment]
The site is on again. 
Thanks.
