### ISSUE TITLE
Customization problem

### ISSUE THREAD

**Issue by floyd168** [steveseguin/twitch-youtube-restream-chat-overlay#9]
I've followed your instruction to stylize the chat message overlay, but only the size was changed. All other color didn't change.
Where did I go wrong?  Thank you for your help!
![螢幕擷取畫面 2021-12-01 173231](https://user-images.githubusercontent.com/83258940/144211884-3e1c1dce-26c4-4191-befc-c8718d82dc82.png)

**Comment by steveseguin** [comment]
what file did you edit?

**Comment by steveseguin** [comment]
if you are able to share the code you are changing as text with me, I can test more easily on my end. Looking at the code quickly, it looks okay, but there might be some color variables that are broken still.

You of course also want to load the file off the disk, and not from the chat.overly.ninja domain, as that would bypass the changes.

**Comment by floyd168** [comment]
[index.zip](https://github.com/steveseguin/twitch-youtube-restream-chat-overlay/files/7632954/index.zip)
Thanks for your kindly support.
I think I loaded the right file, so I can see the size of font and author avatar picture was changed

**Comment by floyd168** [comment]
Thanks again, It's worked.
The mistake that I made is there are two session ID, the first one was wrong.
After changed to second ID, all problem was solved.
Sorry to disturb you!

**Comment by steveseguin** [comment]
No problems at all.  have a good one.
